spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/dahp
    username: dahp
    password: dahp_local_dev
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: Asia/Seoul
    open-in-view: false
    show-sql: true
